version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${BD_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
